services:
  - type: web
    name: discord-ticket-bot
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: discord-bot-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: discord-bot-db
    databaseName: discord_tickets
    user: discord_bot