services:
  - type: worker
    name: ticket-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false  # Ajoute la valeur via l’interface Render pour plus de sécurité
